CREATE DATABASE IF NOT EXISTS cinerank;
USE cinerank;

CREATE TABLE ranking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tmdb_id INT NOT NULL UNIQUE,
  titulo VARCHAR(255) NOT NULL,
  poster VARCHAR(500),
  ano YEAR,
  posicao INT NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);